# Generated by Django 5.0.3 on 2024-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='students/profile_pics/male.png', null=True, upload_to='students/profile_pics'),
        ),
    ]
