# Generated by Django 5.0.3 on 2024-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_description_classroom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'classroom', 'verbose_name_plural': 'classrooms'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
