# Generated by Django 5.0.3 on 2024-03-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_options_alter_classroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
