# Generated by Django 5.0.3 on 2024-03-24 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_classroom_code_classroom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
