# Generated by Django 5.0.3 on 2024-03-24 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_classroom_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=10, verbose_name=django.core.validators.MinLengthValidator(6)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='password',
            field=models.CharField(max_length=20, verbose_name=django.core.validators.MinLengthValidator(8)),
        ),
    ]
