# Generated by Django 5.0.3 on 2024-03-24 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_classroom_code_alter_classroom_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
