# Generated by Django 5.0.3 on 2024-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_assignment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_submission_allow',
            field=models.BooleanField(default=False),
        ),
    ]
