# Generated by Django 5.0.3 on 2024-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
        ('classroom', '0017_assignment_late_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classroom_students', to='accounts.userprofile'),
        ),
    ]
