# Generated by Django 5.0.3 on 2024-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_rename_submission_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='late_submission',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='late_submission',
            field=models.BooleanField(default=False),
        ),
    ]
