# Generated by Django 5.0.3 on 2024-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_remove_assignment_late_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='completed',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
