# Generated by Django 5.0.3 on 2024-04-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0025_assignmentsubmission_is_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_approve',
        ),
    ]
