# Generated by Django 5.0.3 on 2024-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_rename_is_approve_assignmentsubmission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
