# Generated by Django 5.0.3 on 2024-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0030_announcement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
