# Generated by Django 5.0.3 on 2024-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
        ('classroom', '0031_announcement_read_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='read_status',
        ),
        migrations.AddField(
            model_name='announcement',
            name='read_status',
            field=models.ManyToManyField(related_name='students_read', to='accounts.userprofile'),
        ),
    ]
