# Generated by Django 5.0.3 on 2024-04-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0033_announcement_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
