# Generated by Django 5.0.3 on 2024-04-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0035_studentclassroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('video_link', models.URLField(max_length=1000)),
                ('notes', models.FileField(blank=True, null=True, upload_to='class/LectureNotes')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.playlist')),
            ],
            options={
                'verbose_name': 'VideoLecture',
                'verbose_name_plural': 'VideoLectures',
            },
        ),
    ]
