# Generated by Django 5.0.3 on 2024-04-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0036_playlist_videolecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tutor_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
