# Generated by Django 5.0.3 on 2024-04-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0038_videolecture_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
