# Generated by Django 5.0.3 on 2024-04-25 16:34

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0039_alter_announcement_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
