# Generated by Django 5.0.3 on 2024-04-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0040_alter_videolecture_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='notes',
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_file', models.FileField(upload_to='class/LectureNotes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to='classroom.videolecture')),
            ],
            options={
                'verbose_name': 'Lecture Note',
                'verbose_name_plural': 'Lecture Notes',
            },
        ),
    ]
