# Generated by Django 5.0.3 on 2024-04-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0041_remove_videolecture_notes_lecturenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lectures', to='classroom.playlist'),
        ),
    ]
