# Generated by Django 5.0.3 on 2024-09-13 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0044_alter_announcement_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name=django.core.validators.MinLengthValidator(6)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='password',
            field=models.CharField(max_length=16, unique=True, verbose_name=django.core.validators.MinLengthValidator(8)),
        ),
    ]
