# Generated by Django 5.1.1 on 2024-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0046_classroom_requests_alter_classroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='class_coverpics'),
        ),
    ]
