# Generated by Django 5.1.1 on 2024-09-26 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0051_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 6, 7, 18, 387967, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
