# Generated by Django 5.1.1 on 2024-09-30 06:45

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_country'),
        ('classroom', '0057_alter_lecture_order_alter_section_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='quizoptions',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lecture',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='attatchment',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_type',
        ),
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 30, 6, 45, 17, 503544, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='class/lectures/video'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.lecture')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classroom.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizOptions',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
