# Generated by Django 5.1.1 on 2024-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0058_remove_quiz_lecture_remove_quizoptions_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='sample lecture', max_length=150),
            preserve_default=False,
        ),
    ]
