# Generated by Django 5.1.1 on 2024-10-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_country'),
        ('classroom', '0059_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentLecturesProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
