# Generated by Django 5.1.1 on 2024-10-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_country'),
        ('classroom', '0060_lecture_slug_studentlecturesprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default='lecture-111-details-2222', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentLectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('lecture', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='StudentLecturesProgress',
        ),
    ]
