# Generated by Django 5.1.1 on 2024-10-03 17:04

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_country'),
        ('classroom', '0061_alter_lecture_slug_studentlectureprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlectureprogress',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 17, 4, 6, 46618, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
                ('upvote', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.lecture')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classroom.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
