# Generated by Django 5.1.1 on 2024-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0062_studentlectureprogress_timestamp_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlectureprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
