# Generated by Django 5.1.1 on 2024-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0063_alter_studentlectureprogress_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class/lectures/comments'),
        ),
    ]
