# Generated by Django 5.1.1 on 2024-10-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0066_comment_upvoted_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={},
        ),
    ]
